version: '3'

services:
    event_store:
        build: ./postgres
        image: 'postgres-custom-13.2-alpine'
        environment:
            - POSTGRES_USER=root
            - POSTGRES_PASSWORD=root
        ports:
            - '5432:5432'
    meeting_db:
        image: 'mongo:4.0.22'
        restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=root
            - MONGO_INITDB_ROOT_PASSWORD=root
            - MONGO_INITDB_DATABASE=meeting
        ports:
            - '27017:27017'
    message_broker:
        image: 'rabbitmq:3.8'
        environment:
            - RABBITMQ_DEFAULT_USER=root
            - RABBITMQ_DEFAULT_PASS=root
        ports:
            - '5672:5672'
    meeting_svc:
        build: ./meeting-svc
        ports:
            - '8081:8081'
        environment:
            - SPRING_DATASOURCE_URL=jdbc:postgresql://event_store/meeting
        depends_on:
            - event_store
            - message_broker
    meeting_read_svc:
        build: ./meeting-read-svc
        ports:
            - '8082:8082'
        environment:
            - SPRING_DATA_MONGODB_URI=mongodb://root:root@meeting_db/meeting
        depends_on:
            - meeting_db
            - message_broker
