server:
    port: 8082
spring:
    profiles.active: dev
    application:
        name: meeting-read-svc
    jackson:
        default-property-inclusion: NON_NULL
        serialization:
            write-dates-as-timestamps: false
logging:
    level:
        org:
            springframework:
                web: debug